### ISSUE TITLE
migration failing

### ISSUE THREAD

**Issue by perfecto25** [JFrogDev/nexus2artifactory#1]
trying to migrate a test repo from Nexus (v. 2.11.2 ) to Artif (v 4.10.0)

from log, 

```

[nexus@njc02 nexus2artifactory-master]$ cat mylog 
============================================================

Nexus To Artifactory Migration Tool

============================================================

2016-10-31 15:46:12,431 [MainThread] [INFO] (root:14) - Initializing Nexus migration tool.
2016-10-31 15:46:12,438 [MainThread] [INFO] (nex2art.menu.Setup:41) - Sending system ping to Artifactory.
2016-10-31 15:46:12,439 [MainThread] [INFO] (nex2art.menu.Setup:83) - System ping completed, status: None.
2016-10-31 15:46:17,784 [MainThread] [INFO] (nex2art.menu.Main:111) - Loading configuration from file mrx.
2016-10-31 15:46:17,838 [MainThread] [INFO] (nex2art.core.Nexus:28) - Reading Nexus config from /data/sonatype-work/nexus/conf/nexus.xml.
2016-10-31 15:46:17,851 [MainThread] [INFO] (nex2art.core.Nexus:53) - Successfully read Nexus config.
2016-10-31 15:46:17,851 [MainThread] [INFO] (nex2art.core.Ldap:15) - Reading LDAP config from /data/sonatype-work/nexus/conf/ldap.xml.
2016-10-31 15:46:17,852 [MainThread] [INFO] (nex2art.core.Ldap:19) - Successfully read LDAP config.
2016-10-31 15:46:17,852 [MainThread] [INFO] (nex2art.core.Security:29) - Reading security config from /data/sonatype-work/nexus/conf/security.xml.
2016-10-31 15:46:17,855 [MainThread] [INFO] (nex2art.core.Security:50) - Successfully read security config.
2016-10-31 15:46:17,855 [MainThread] [INFO] (nex2art.menu.Setup:41) - Sending system ping to Artifactory.
2016-10-31 15:46:17,855 [MainThread] [INFO] (nex2art.menu.Setup:53) - Sending request to https://artifactory.mycompany.local/api/system/ping.
2016-10-31 15:46:18,496 [MainThread] [INFO] (nex2art.menu.Setup:83) - System ping completed, status: 200.
2016-10-31 15:46:18,517 [MainThread] [INFO] (nex2art.menu.Main:118) - Configuration loaded successfully.
2016-10-31 15:46:57,666 [MainThread] [INFO] (nex2art.menu.Main:54) - Verifying current state.
2016-10-31 15:46:57,668 [MainThread] [INFO] (nex2art.core.Nexus:28) - Reading Nexus config from /data/sonatype-work/nexus/conf/nexus.xml.
2016-10-31 15:46:57,679 [MainThread] [INFO] (nex2art.core.Nexus:53) - Successfully read Nexus config.
2016-10-31 15:46:57,679 [MainThread] [INFO] (nex2art.core.Ldap:15) - Reading LDAP config from /data/sonatype-work/nexus/conf/ldap.xml.
2016-10-31 15:46:57,680 [MainThread] [INFO] (nex2art.core.Ldap:19) - Successfully read LDAP config.
2016-10-31 15:46:57,680 [MainThread] [INFO] (nex2art.core.Security:29) - Reading security config from /data/sonatype-work/nexus/conf/security.xml.
2016-10-31 15:46:57,682 [MainThread] [INFO] (nex2art.core.Security:50) - Successfully read security config.
2016-10-31 15:46:57,682 [MainThread] [INFO] (nex2art.menu.Setup:41) - Sending system ping to Artifactory.
2016-10-31 15:46:57,682 [MainThread] [INFO] (nex2art.menu.Setup:53) - Sending request to https://artifactory.mycompany.local/api/system/ping.
2016-10-31 15:46:57,702 [MainThread] [INFO] (nex2art.menu.Setup:83) - System ping completed, status: 200.
2016-10-31 15:46:57,705 [MainThread] [INFO] (nex2art.menu.Main:56) - Current state verified successfully.
2016-10-31 15:47:00,372 [MainThread] [INFO] (nex2art.menu.Main:64) - Attempting to run migration.
2016-10-31 15:47:00,375 [MainThread] [INFO] (nex2art.core.Nexus:28) - Reading Nexus config from /data/sonatype-work/nexus/conf/nexus.xml.
2016-10-31 15:47:00,386 [MainThread] [INFO] (nex2art.core.Nexus:53) - Successfully read Nexus config.
2016-10-31 15:47:00,386 [MainThread] [INFO] (nex2art.core.Ldap:15) - Reading LDAP config from /data/sonatype-work/nexus/conf/ldap.xml.
2016-10-31 15:47:00,387 [MainThread] [INFO] (nex2art.core.Ldap:19) - Successfully read LDAP config.
2016-10-31 15:47:00,387 [MainThread] [INFO] (nex2art.core.Security:29) - Reading security config from /data/sonatype-work/nexus/conf/security.xml.
2016-10-31 15:47:00,388 [MainThread] [INFO] (nex2art.core.Security:50) - Successfully read security config.
2016-10-31 15:47:00,389 [MainThread] [INFO] (nex2art.menu.Setup:41) - Sending system ping to Artifactory.
2016-10-31 15:47:00,389 [MainThread] [INFO] (nex2art.menu.Setup:53) - Sending request to https://artifactory.mycompany.local/api/system/ping.
2016-10-31 15:47:00,408 [MainThread] [INFO] (nex2art.menu.Setup:83) - System ping completed, status: 200.
2016-10-31 15:47:00,413 [MainThread] [INFO] (nex2art.core.Artifactory:47) - Migrating to Artifactory.
2016-10-31 15:47:00,414 [MainThread] [INFO] (nex2art.core.Artifactory:53) - Enabling password expiration.
2016-10-31 15:47:00,414 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending GET request to https://artifactory.mycompany.local/api/system/configuration.
2016-10-31 15:47:00,549 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending POST request to https://artifactory.mycompany.local/api/system/configuration.
2016-10-31 15:47:00,787 [MainThread] [INFO] (nex2art.core.Artifactory:133) - Migrating repository definitions.
2016-10-31 15:47:00,787 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending GET request to https://artifactory.mycompany.local/api/repositories.
2016-10-31 15:47:01,618 [MainThread] [INFO] (nex2art.core.Artifactory:144) - Migrating repo Install4J -> mrepo_test.
2016-10-31 15:47:01,619 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending POST request to https://artifactory.mycompany.local/api/repositories/mrepo_test.
2016-10-31 15:47:01,695 [MainThread] [ERROR] (nex2art.core.Artifactory:388) - Error making request:
Traceback (most recent call last):
  File "/opt/nexus2artif/nexus2artifactory-master/nex2art/core/Artifactory.py", line 384, in dorequest
    resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 409: Conflict
2016-10-31 15:47:01,696 [MainThread] [ERROR] (nex2art.core.Artifactory:168) - Error migrating repository Install4J:
Traceback (most recent call last):
  File "/opt/nexus2artif/nexus2artifactory-master/nex2art/core/Artifactory.py", line 166, in migraterepos
    self.dorequest(conn, mthd, cfg, jsn)
  File "/opt/nexus2artif/nexus2artifactory-master/nex2art/core/Artifactory.py", line 395, in dorequest
    raise MigrationError(msg)
MigrationError
2016-10-31 15:47:01,696 [MainThread] [INFO] (nex2art.core.Artifactory:219) - Migrating groups.
2016-10-31 15:47:01,696 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending GET request to https://artifactory.mycompany.local/api/security/groups.
2016-10-31 15:47:01,715 [MainThread] [INFO] (nex2art.core.Artifactory:173) - Migrating users.
2016-10-31 15:47:01,715 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending GET request to https://artifactory.mycompany.local/api/security/users.
2016-10-31 15:47:01,735 [MainThread] [INFO] (nex2art.core.Artifactory:246) - Migrating permissions.
2016-10-31 15:47:01,735 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending GET request to https://artifactory.mycompany.local/api/security/permissions.
2016-10-31 15:47:01,757 [MainThread] [INFO] (nex2art.core.Artifactory:64) - Resetting password expiration.
2016-10-31 15:47:01,757 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending GET request to https://artifactory.mycompany.local/api/system/configuration.
2016-10-31 15:47:01,892 [MainThread] [INFO] (nex2art.core.Artifactory:382) - Sending POST request to https://artifactory.mycompany.local/api/system/configuration.
2016-10-31 15:47:02,182 [MainThread] [INFO] (nex2art.core.Upload:28) - Uploading artifacts.
2016-10-31 15:47:02,183 [MainThread] [INFO] (nex2art.core.Upload:34) - Creating 4 threads.
2016-10-31 15:47:02,183 [MainThread] [INFO] (nex2art.core.Upload:39) - Threads created successfully.
2016-10-31 15:47:02,184 [MainThread] [INFO] (nex2art.core.Upload:43) - All artifacts successfully uploaded.
2016-10-31 15:47:14,122 [MainThread] [INFO] (nex2art.menu.Main:71) - Migration successfully run.
2016-10-31 15:47:26,357 [MainThread] [INFO] (root:33) - Terminating Nexus migration tool.

```

**Comment by perfecto25** [comment]
was an issue with my network, ignore

**Comment by perfecto25** [comment]
verified nexus server can talk to artifactory, ports are open, still getting same error

**Comment by peters95** [comment]
closing this issue due to age
