### ISSUE TITLE
Error in Initial Set up

### ISSUE THREAD

**Issue by lekshmimadhu** [JFrogDev/nexus2artifactory#22]
Hi,
I have installed nexus2artifactory tool on the same server where Nexus is installed. Python version is 2.6.6.

While trying to do initial setup, once 'Nexus Data Directory' details are given, I am getting error "AttributeError: 'NoneType' object has no attribute 'text'"

Nexus path provided is: sonatype-work/nexus

Could you please check on how to resolve this issue.
Error details given below:
----------------------------------------------
Traceback (most recent call last):
  File "./NexusToArtifactory.py", line 70, in <module>
    else: initInteractive(setup)
  File "./NexusToArtifactory.py", line 27, in initInteractive
    win.show()
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Menu.py", line 179, in show
    if self.runact(sel, sel['act']): return
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Menu.py", line 202, in runact
    elif hasattr(act, 'show'): act.show()
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Menu.py", line 179, in show
    if self.runact(sel, sel['act']): return
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Menu.py", line 203, in runact
    elif hasattr(act, '__call__'): cont = self.showCall(sel, act)
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Menu.py", line 223, in showCall
    cont = act(sel)
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/menu/Setup.py", line 9, in nx
    def nx(_): return self.scr.nexus.checkNexus()
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Nexus.py", line 48, in checkNexus
    self._nex2.checkNexus()
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Nexus2.py", line 137, in checkNexus
    nx.vpath = self.refresh(newpath)
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Nexus2.py", line 26, in refresh
    caps = self.getYumCapabilities(xmlcap)
  File "/opt/app/lmadhu/nexus2artifactory-master/nex2art/core/Nexus2.py", line 129, in getYumCapabilities
    props[prop.find('key').text] = prop.find('value').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by DarthFennec** [comment]
These kinds of errors happen every so often. The migrator reads your Nexus config xml files, and expects to find certain information, but sometimes that information isn't there (because someone modified the xml by hand, or for some other reason), and that causes the tool to panic.

In your case, it appears that the tool is encountering an issue while reading the `capabilities.xml` file. One of your `<capability>` entries has a `<property>` that is missing either a `<key>` or a `<value>`, which is invalid as far as I can tell. If you could look at this file and locate the offending property, that would verify the issue, and we can decide on the best course of action from there.

**Comment by peters95** [comment]
Closing this issue due to age
