### ISSUE TITLE
409 doesn't match the POM's

### ISSUE THREAD

**Issue by edaraanand** [JFrogDev/nexus2artifactory#37]
We selected option 'p' i.e. Suppresses Pom Consistency Checks - Whether this repository disables checking for inconsistencies with pom files before allowing artifacts to be deployed. Local and remote repositories only and executed the migration and got below error. Can you please suggest how can I avoid this error.

2019-02-15 13:21:38,542 [Thread-3] [ERROR] (nex2art.core.Upload:244) - Unable to deploy artifact to https://staging.artifacts.excompany.net/artifactory/billing-maven-local/.nexus/trash/org/springframework/Spring/3.0.0.M3/Spring-3.0.0.M3.pom.
2019-02-15 13:21:38,681 [Thread-3] [ERROR] (nex2art.core.Upload:288) - Error deploying artifact checksum:
{
"errors" : [ {
"status" : 409,
"message" : "The target deployment path '.nexus/trash/org/springframework/Spring/3.0.0.M3/Spring-3.0.0.M3.pom' does not match the POM's expected path prefix 'org/springframework/Spring/3.0.0.M3'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."
} ]
}
Traceback (most recent call last):
File "/root/nexus2artifactory-master/nex2art/core/Upload.py", line 282, in deployChecksum
else: stat = urllib2.urlopen(req).getcode()
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib64/python2.7/urllib2.py", line 475, in error
return self._call_chain(*args)
File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 409: Conflict
2019-02-15 13:21:38,683 [Thread-3] [ERROR] (nex2art.core.Upload:244) - Unable to deploy artifact to https://staging.artifacts.excompany.net/artifactory/billing-maven-local/.nexus/trash/org/springframework/Spring/3.0.0.M3/Spring-3.0.0.M3.pom.
2019-02-15 13:21:38,838 [Thread-3] [ERROR] (nex2art.core.Upload:288) - Error deploying artifact checksum:
{
"errors" : [ {
"status" : 409,
"message" : "The target deployment path '.nexus/trash/org/springframework/Spring/3.0.0.M3/Spring-3.0.0.M3.pom' does not match the POM's expected path prefix 'org/springframework/Spring/3.0.0.M3'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."
} ]
}
Traceback (most recent call last):
File "/root/nexus2artifactory-master/nex2art/core/Upload.py", line 282, in deployChecksum
else: stat = urllib2.urlopen(req).getcode()
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib64/python2.7/urllib2.py", line 475, in error
return self._call_chain(*args)
File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 409: Conflict
2019-02-15 13:21:38,839 [Thread-3] [ERROR] (nex2art.core.Upload:244) - Unable to deploy artifact to https://staging.artifacts.excompany.net/artifactory/billing-maven-local/.nexus/trash/org/springframework/Spring/3.0.0.M3/Spring-3.0.0.M3.pom.
2019-02-15 13:21:38,840 [Thread-3] [ERROR] (nex2art.core.Upload:249) - Unable to deploy artifact to https://staging.artifacts.excompany.net/artifactory/billing-maven-local/.nexus/trash/org/springframework/Spring/3.0.0.M3/Spring-3.0.0.M3.pom after 3 retries.
2019-02-15 13:21:42,755 [MainThread] [ERROR] (nex2art.core.Artifactory:582) - Error making request:
{
"errors" : [ {
"status" : 403,
"message" : "Forbidden"
} ]
}
Traceback (most recent call last):
File "/root/nexus2artifactory-master/nex2art/core/Artifactory.py", line 578, in dorequest
else: resp = urllib2.urlopen(req)
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python2.7/urllib2.py", line 437, in open
response = meth(req, response)
File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib64/python2.7/urllib2.py", line 475, in error
return self._call_chain(*args)
File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
2019-02-15 13:21:42,755 [MainThread] [ERROR] (nex2art.core.Artifactory:263) - Error finalizing migration for repository thirdparty:
Traceback (most recent call last):
File "/root/nexus2artifactory-master/nex2art/core/Artifactory.py", line 261, in migratereposfinalize
self.dorequest(conn, 'POST', cfg, jsn)
File "/root/nexus2artifactory-master/nex2art/core/Artifactory.py", line 589, in dorequest
raise MigrationError(msg)
MigrationError

**Comment by peters95** [comment]
Closing issue due to age
