### ISSUE TITLE
Nexus OSS 3.13.0-01 connection problems

### ISSUE THREAD

**Issue by Grejeru** [JFrogDev/nexus2artifactory#42]
Hi,
When I'm configuring script  to start migration, I got green on data directory, then green on url, user and password, but data directory turns red.
I have run script with logging and I see few errors, but I think most important are

```
2019-07-17 17:40:51,376 [MainThread] [ERROR] (nex2art.core.Nexus3:239) - Error connecting to Nexus:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
Traceback (most recent call last):
  File "/var/lib/docker/volumes/prod_nexus_data/_data/nexus2artifactory/nex2art/core/Nexus3.py", line 235, in dorequest
    else: resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 411: Length Required
```

```
2019-07-17 17:40:41,022 [MainThread] [ERROR] (nex2art.core.Nexus3:239) - Error connecting to Nexus:
Traceback (most recent call last):
  File "/var/lib/docker/volumes/prod_nexus_data/_data/nexus2artifactory/nex2art/core/Nexus3.py", line 235, in dorequest
    else: resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 635, in http_error_302
    new = self.redirect_request(req, fp, code, msg, headers, newurl)
  File "/usr/lib64/python2.7/urllib2.py", line 596, in redirect_request
    raise HTTPError(req.get_full_url(), code, msg, headers, fp)
HTTPError: HTTP Error 302: Found
```

What is more important, Nexus is configured with Azure Active Directory so there might be some issue with redirect links (even that I have provided local admin account to login).
Nexus instance is installed from sonatype/nexus3 docker image.

**Comment by DarthFennec** [comment]
I don't know much about Azure AD, but if it's set up in front of Nexus as a reverse proxy (or if some other service is), it may be modifying headers in a way that causes these issues. This seems unlikely, but I can't think of an explanation that would be more likely at the moment. Is there a way for you to try connecting to Nexus directly? If so, you can give that a try, and see if it changes anything.

If you could, I'd also like to know a few things about your setup, so I might be able to try and reproduce your situation more accurately. Specifically, what version of Python are you using, and what OS/distribution are you running? How was Python installed, if you know?

Thanks!
