### ISSUE TITLE
Dockerized Nexus3 to ArtifactoryPro

### ISSUE THREAD

**Issue by kb7791** [JFrogDev/nexus2artifactory#61]
Trying to use the migration tool on a machine that has a dockerized Nexus running on it. The Dockerized nexus is bind mounted to a local directory outside the container. Lets say the absolute path to that bind mount is /home/me/nexus-data. That home/me/nexus-data consists of the directory structure:

![image](https://user-images.githubusercontent.com/11503681/89466906-a8eae080-d742-11ea-9738-08b3ca3fd344.png)

For some reason, when I point the migration tool at that path, I get this error.
![image](https://user-images.githubusercontent.com/11503681/89467156-1a2a9380-d743-11ea-9441-f607a88ff37e.png)

The path was green till I entered my Nexus credentials and then suddenly went red, my creds in nexus are set to admin so its not a permission issue.

**Comment by kb7791** [comment]
0-08-05 20:17:48,748 [MainThread] [INFO] (nex2art.core.Format:124) - Updating data tree with Nexus data.
2020-08-05 20:17:48,749 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/Initial Setup/Nexus Username'.
2020-08-05 20:17:50,571 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'c' pressed.
2020-08-05 20:17:55,905 [MainThread] [DEBUG] (nex2art.core.Screen:137) - Key '*' pressed.
2020-08-05 20:17:56,388 [MainThread] [DEBUG] (nex2art.core.Screen:137) - Key '*' pressed.
2020-08-05 20:17:56,950 [MainThread] [DEBUG] (nex2art.core.Screen:137) - Key '*' pressed.
2020-08-05 20:18:02,091 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'ENTER' pressed.
2020-08-05 20:18:02,093 [MainThread] [INFO] (nex2art.core.Nexus3:195) - Sending system ping to Nexus.
2020-08-05 20:18:02,093 [MainThread] [INFO] (nex2art.core.Nexus3:206) - Sending request to http://nexus:8081/service/metrics/ping.
2020-08-05 20:18:02,296 [MainThread] [INFO] (nex2art.core.Nexus3:237) - System ping completed, status: 200.
2020-08-05 20:18:02,296 [MainThread] [INFO] (nex2art.core.Nexus3:42) - Reading repository config from Nexus.
2020-08-05 20:18:02,297 [MainThread] [INFO] (nex2art.core.Nexus3:147) - Attempting to communicate with Nexus server.
2020-08-05 20:18:02,311 [MainThread] [INFO] (nex2art.core.Nexus3:167) - Deploying extraction plugin to Nexus.
2020-08-05 20:18:02,320 [MainThread] [ERROR] (nex2art.core.Nexus3:252) - Error connecting to Nexus:
{
  "name" : "artifactorymigrator",
  "result" : "Creating and updating scripts is disabled"
}
Traceback (most recent call last):
  File "/home/me/nexus2artifactory/nex2art/core/Nexus3.py", line 248, in dorequest
    else: resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 410: Gone
2020-08-05 20:18:02,320 [MainThread] [INFO] (nex2art.core.Nexus3:257) - http://nexus:8081/service/rest/v1/script responded with 410.
2020-08-05 20:18:02,320 [MainThread] [ERROR] (nex2art.core.Nexus3:260) - Unable to deploy Nexus plugin: 410.
2020-08-05 20:18:02,321 [MainThread] [ERROR] (nex2art.core.Nexus3:178) - Error accessing Nexus instance: Unable to deploy Nexus plugin: 410.
2020-08-05 20:18:02,321 [MainThread] [INFO] (nex2art.core.Nexus3:46) - Retrying with older Nexus API.
2020-08-05 20:18:02,321 [MainThread] [INFO] (nex2art.core.Nexus3:147) - Attempting to communicate with Nexus server.
2020-08-05 20:18:02,321 [MainThread] [INFO] (nex2art.core.Nexus3:167) - Deploying extraction plugin to Nexus.
2020-08-05 20:18:02,330 [MainThread] [ERROR] (nex2art.core.Nexus3:252) - Error connecting to Nexus:

<!DOCTYPE html>
<html lang="en">
<head>
  <title>405 - Nexus Repository Manager</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>


  
  <link rel="icon" type="image/png" href="http://nexus:8081/favicon-32x32.png?3.22.0-02" sizes="32x32">
  <link rel="mask-icon" href="http://nexus:8081/safari-pinned-tab.svg?3.22.0-02" color="#5bbad5">
  <link rel="icon" type="image/png" href="http://nexus:8081/favicon-16x16.png?3.22.0-02" sizes="16x16">
  <link rel="shortcut icon" href="http://nexus:8081/favicon.ico?3.22.0-02">
  <meta name="msapplication-TileImage" content="http://nexus:8081/mstile-144x144.png?3.22.0-02">
  <meta name="msapplication-TileColor" content="#00a300">

  <link rel="stylesheet" type="text/css" href="http://nexus:8081/static/css/nexus-content.css?3.22.0-02"/>
</head>
<body>
<div class="nexus-header">
  <a href="http://nexus:8081">
    <div class="product-logo">
      <img src="http://nexus:8081/static/images/nexus.png?3.22.0-02" alt="Product logo"/>
    </div>
    <div class="product-id">
      <div class="product-id__line-1">
        <span class="product-name">Nexus Repository Manager</span>
      </div>
      <div class="product-id__line-2">
        <span class="product-spec">OSS 3.22.0-02</span>
      </div>
    </div>
  </a>
</div>

<div class="nexus-body">
  <div class="content-header">
    <img src="http://nexus:8081/static/rapture/resources/icons/x32/exclamation.png?3.22.0-02" alt="Exclamation point" aria-role="presentation"/>
    <span class="title">Error 405</span>
    <span class="description">Method Not Allowed</span>
  </div>
  <div class="content-body">
    <div class="content-section">
      HTTP method POST is not supported by this URL
    </div>
      </div>
</div>
</body>
</html>

Traceback (most recent call last):
  File "/home/me/nexus2artifactory/nex2art/core/Nexus3.py", line 248, in dorequest
    else: resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 405: HTTP method POST is not supported by this URL
2020-08-05 20:18:02,331 [MainThread] [INFO] (nex2art.core.Nexus3:257) - http://nexus:8081/service/siesta/rest/v1/script responded with 405.
2020-08-05 20:18:02,331 [MainThread] [ERROR] (nex2art.core.Nexus3:260) - Unable to deploy Nexus plugin: 405.
2020-08-05 20:18:02,332 [MainThread] [ERROR] (nex2art.core.Nexus3:178) - Error accessing Nexus instance: Unable to deploy Nexus plugin: 405.
2020-08-05 20:18:02,332 [MainThread] [INFO] (nex2art.core.Format:124) - Updating data tree with Nexus data.
2020-08-05 20:18:02,333 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/Initial Setup/Nexus Password'.

**Comment by kb7791** [comment]
missed this fix in instructions, nexus.scripts.allowCreation=true, that seemed to fix the issue
