### ISSUE TITLE
found duplicated key 'artifactorymigrator' in index 'script_name_idx' previously assigned to the record #133:11

### ISSUE THREAD

**Issue by MichaelPak** [JFrogDev/nexus2artifactory#69]
I'm trying migrate artifacts from Nexus3 to Artifactory. When I'm configuring connection to the Nexus, there is an error in the logs:
```
2021-01-18 10:08:30,416 [MainThread] [INFO] (nex2art.core.Nexus3:42) - Reading repository config from Nexus.
2021-01-18 10:08:30,416 [MainThread] [INFO] (nex2art.core.Nexus3:147) - Attempting to communicate with Nexus server.
2021-01-18 10:08:30,417 [MainThread] [INFO] (nex2art.core.Nexus3:167) - Deploying extraction plugin to Nexus.
2021-01-18 10:08:30,468 [MainThread] [ERROR] (nex2art.core.Nexus3:252) - Error connecting to Nexus:
ERROR: (ID bce9f206-18f2-46cc-9175-3e5af8bfcd30) com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #134:11: found duplicated key 'artifactorymigrator' in index 'script_name_idx' previously assigned to the record #133:11
        DB name="config" INDEX=script_name_idx RID=#133:11
Traceback (most recent call last):
  File "/opt/nexus2artifactory/nex2art/core/Nexus3.py", line 248, in dorequest
    else: resp = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Server Error
2021-01-18 10:08:30,469 [MainThread] [INFO] (nex2art.core.Nexus3:257) - https://nexus-url/service/rest/v1/script responded with 500.
2021-01-18 10:08:30,469 [MainThread] [ERROR] (nex2art.core.Nexus3:260) - Unable to deploy Nexus plugin: 500.
2021-01-18 10:08:30,469 [MainThread] [ERROR] (nex2art.core.Nexus3:178) - Error accessing Nexus instance: Unable to deploy Nexus plugin: 500.
```

**Comment by MichaelPak** [comment]
I haven't got any scripts in Nexus3:
```
❯ curl -u user:pass https://nexus-url/service/rest/v1/script
[ ]%
```

**Comment by MichaelPak** [comment]
I deleted migration script manually through [REST API](https://help.sonatype.com/repomanager3/rest-and-integration-api/script-api). And it works!
