### ISSUE TITLE
Unable to run the migrating script on windows env.  Encountered the error: unknown encoding: cp65001, 

### ISSUE THREAD

**Issue by lzwzzy** [JFrogDev/nexus2artifactory#73]
Traceback (most recent call last):
  File "NexusToArtifactory.py", line 70, in <module>
  File "NexusToArtifactory.py", line 27, in initInteractive
  File "nex2art\core\Menu.py", line 166, in show
  File "nex2art\core\Menu.py", line 124, in render
  File "unicurses.py", line 771, in waddstr
  File "unicurses.py", line 114, in CSTR
LookupError: unknown encoding: cp65001
[79476] Failed to execute script NexusToArtifactory

**Comment by lzwzzy** [comment]
I'm in Windows10，Nexus3
